---
title: "p8105_hw6_yz4187"
author: "Yiwen Zhao"
date: "12/4/2021"
output: github_document
---

```{r, message=FALSE}
library(tidyverse)
library(modelr)
library(purrr)
library(mgcv)
library(ggplot2)
library(patchwork)
set.seed(1)
```

## Problem 1 ##

*Data cleaning:*
```{r, results='hide'}
birthweight = read.csv("./birthweight.csv")

birthweight %>%
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(babysex = factor(babysex, labels = c("male", "female")),
         frace = factor(frace, levels = c(1, 2, 3, 4, 8, 9),
                        labels = c("White", "Black", "Asian", "PuertoRican", "Other", "Unknown")),
         malform = factor(malform, levels = c(0, 1),
                          labels = c("absent", "present")),
         mrace = factor(mrace, levels = c(1, 2, 3, 4, 8),
                        labels = c("White", "Black", "Asian", "PuertoRican", "Other"))
         )

```

*Regression Model:*
```{r}
bw_df = lm(bwt ~ smoken + wtgain + bhead + blength + mrace + gaweeks, data = birthweight)
bw_df%>% 
  broom::tidy() %>% 
  select(term, estimate, p.value) %>% 
  mutate(term = str_replace(term, "^mrace", "mom_race: ")) %>% 
  knitr::kable(digits = 3)

reg_model = modelr::add_residuals(birthweight, bw_df)
reg_model = modelr::add_predictions(reg_model, bw_df)
reg_model %>% 
  ggplot(aes(x = pred, y = resid, color = resid)) + 
  geom_point(alpha = .5) + 
  theme(legend.position = "right") +
  labs(
    x = "Fitted Values",
    y = "Model Residuals",
    title = "Plot: Regression Model"
  )
```

*Comparison with two other models:*
```{r}
bw_df1 = lm(bwt ~ blength + gaweeks, data = birthweight)
bw_df2 = lm(bwt ~ bhead + blength + babysex + bhead * blength + bhead * babysex + blength * bhead + bhead * blength * babysex, data = birthweight)

crossv = 
  crossv_mc(birthweight, 100) %>% 
  mutate(
    own_model = map(train, ~lm(bwt ~ smoken + wtgain + bhead + blength + mrace + gaweeks, data = .)),
    comp1 = map(train, ~lm(bwt ~ blength + gaweeks, data = .)),
    comp2 = map(train, ~lm(bwt ~ bhead + blength + babysex + bhead * blength + bhead * babysex + blength * bhead + bhead * blength * babysex, data = .)),
  ) %>% 
  mutate(
    rmse_own_model = map2_dbl(own_model, test, ~rmse(model = .x, data = .y)),
    rmse_comp1 = map2_dbl(comp1, test, ~rmse(model = .x, data = .y)),
    rmse_comp2 = map2_dbl(comp2, test, ~rmse(model = .x, data = .y))
  )

crossv %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model",
    values_to = "rmse",
    names_prefix = "rmse_"
  ) %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse, fill = model)) + 
  geom_violin() +
  labs(
    x = "Models",
    y = "RMSE",
    title = "Model Comprison"
  ) 
```

## Problem 2 ##

```{r, message=FALSE}
library(p8105.datasets)

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

lm(tmax ~ tmin, data = weather_df) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)
```

Estimation 1: r̂ ^2
```{r}
sample1 = weather_df %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::glance)) %>% 
  unnest(results) %>% 
  select(r.squared)
```

Estimation 2: log(β̂ 0∗β̂ 1)
```{r, warning=FALSE}
sample2= weather_df %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::tidy)) %>% 
  select(-strap, -models) %>% 
  unnest(results) %>% 
  select(term, estimate) %>% 
  pivot_wider(
    names_from = "term",
    values_from = "estimate") %>% 
  unnest() %>% 
  janitor::clean_names() %>% 
  mutate(
    log_estimate = log10(intercept * tmin)
  )
```

Making a plot:
```{r, warning=FALSE}
plot1 = 
  sample1 %>% 
  ggplot(aes(x =r.squared)) +
  geom_density(aes(fill = "pink"), size = 1.1) + 
  geom_vline(aes(xintercept = mean(r.squared)), color = "blue", linetype = "dashed", size = 1) +
  labs(title = "Distribution of r square in 5000 sampling",
       x = "R square",
       y = "Density") +
  theme(legend.position = "none")
## The distribution is left-skewed meaning the median is larger than mean
## calculate the CI of r square
quantile(sample1$r.squared, probs = c(0.025, 0.975))

plot2 = 
  sample2 %>% 
  ggplot(aes(x = log_estimate)) +
  geom_density(aes(fill = "yellow"), size = 1.1) +
  geom_vline(aes(xintercept = mean(log_estimate)),
            color = "blue", linetype = "dashed", size = 1) +
  labs(title = "Distribution of log(β̂ 0∗β̂ ) in 5000 sampling",
       x = "log(β̂ 0∗β̂ 1)",
       y = "Density") +
  theme(legend.position = "none")

plot1 + plot2

quantile(sample1$r.squared, c(0.025, 0.975))
quantile(sample2$log_estimate, c(0.025, 0.975))
```

*Description:* The 95% confidence interval of r square is 0.893 at 2.5% quantile and 0.927 at 97.5% quantile. The 95% confidence interval of log(β̂ 0∗β̂ 1)is   0.853 at 2.5% quantile and 0.894 at 97.5% quantile.


